version: '1'
services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - databox-network
    command: ['npm', 'run', 'serve']

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEWS_API_KEY=VEQGN35J4jMNPSVjLzlHWzynyCPaszwjkYtPsd0PYhM
      - CUSTOM_DATA_LIBRARY_TOKEN=nxdo7p4gs4l1r032mcx8
      - NEWS_METRICS_LIBRARY_TOKEN=uoz1oao24x8l93cr4bwh7
      - WEATHER_METRICS_LIBRARY_TOKEN=d600vgl234kcdgl47l26
      - METRIC_TOKEN=Number_of_Bitcoin_News
      - MONGO_DB_CONN_STRING=mongodb+srv://nebojsa:RKiYqou2zWOVXlE1@cluster0.dbfiorp.mongodb.net/test
      - MONGO_DB_NAME=DataBox
      - MONGO_DB_COLLECTION=LoggingData
      - PORT=3000
    networks:
      - databox-network
    command: ['npm', 'start']

networks:
  databox-network:
    driver: bridge
